export const subscribers = [
  {
    id: 1,
    name: "Rupanjan De",
    email: "derupanjan2020@gmail.com",
    subscribedAt: "2024-11-01",
  },
  {
    id: 2,
    name: "Aarav Sharma",
    email: "aarav.sharma@example.com",
    subscribedAt: "2024-10-20",
  },
  {
    id: 3,
    name: "Priya Singh",
    email: "priya.singh@example.com",
    subscribedAt: "2024-09-15",
  },
  {
    id: 4,
    name: "Nisha Patel",
    email: "nisha.patel@example.com",
    subscribedAt: "2024-11-05",
  },
  {
    id: 5,
    name: "Vikram Malhotra",
    email: "vikram.malhotra@example.com",
    subscribedAt: "2024-08-30",
  },
  {
    id: 6,
    name: "Anjali Kapoor",
    email: "anjali.kapoor@example.com",
    subscribedAt: "2024-07-22",
  },
  {
    id: 7,
    name: "Siddharth Roy",
    email: "siddharth.roy@example.com",
    subscribedAt: "2024-10-12",
  },
  {
    id: 8,
    name: "Neha Agarwal",
    email: "neha.agarwal@example.com",
    subscribedAt: "2024-11-03",
  },
  {
    id: 9,
    name: "Rahul Verma",
    email: "rahul.verma@example.com",
    subscribedAt: "2024-10-01",
  },
  {
    id: 10,
    name: "Meera Nair",
    email: "meera.nair@example.com",
    subscribedAt: "2024-09-18",
  },
  {
    id: 11,
    name: "Karan Joshi",
    email: "karan.joshi@example.com",
    subscribedAt: "2024-08-25",
  },
  {
    id: 12,
    name: "Simran Kaur",
    email: "simran.kaur@example.com",
    subscribedAt: "2024-11-06",
  },
  {
    id: 13,
    name: "Arjun Iyer",
    email: "arjun.iyer@example.com",
    subscribedAt: "2024-09-30",
  },
  {
    id: 14,
    name: "Tanvi Desai",
    email: "tanvi.desai@example.com",
    subscribedAt: "2024-10-15",
  },
  {
    id: 15,
    name: "Aditi Reddy",
    email: "aditi.reddy@example.com",
    subscribedAt: "2024-08-10",
  },
  {
    id: 16,
    name: "Rohan Bhatia",
    email: "rohan.bhatia@example.com",
    subscribedAt: "2024-11-02",
  },
  {
    id: 17,
    name: "Pooja Menon",
    email: "pooja.menon@example.com",
    subscribedAt: "2024-10-22",
  },
  {
    id: 18,
    name: "Rajesh Kumar",
    email: "rajesh.kumar@example.com",
    subscribedAt: "2024-09-05",
  },
  {
    id: 19,
    name: "Sneha Suresh",
    email: "sneha.suresh@example.com",
    subscribedAt: "2024-11-04",
  },
  {
    id: 20,
    name: "Vivek Sharma",
    email: "vivek.sharma@example.com",
    subscribedAt: "2024-10-28",
  },
];
